#ifdef __wasm__
#include <wasm_simd128.h>
#else
#define SIMDE_X86_FMA_NATIVE
#include "wasm_simd128_polyfill.h"
#endif

#define unreachable() __builtin_unreachable()
#define likely(x) __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)

// preconditions
// - no NaNs, no subnormals
// - source registers: always finite
// 1. finite - no infinities (register type F, additive instructions)
// 2. zero   - no zero, no negatives, positive infinity (register type E, multiplicative instructions)
//
// fmul_1(possible_inf, never_inf) -> assume RHS is never inf

// `c` can be zero, when zero is generated it is ALWAYS a perfectly rounded operation (generated by x - x == 0)
// that means there is no need for special cases, as it'll be masked out by a (false) `to_round`

v128_t semi_fadd_1(v128_t dest, v128_t src);
v128_t semi_fmul_1(v128_t dest, v128_t src);
v128_t semi_fmul_fma_1(v128_t dest, v128_t src);

v128_t soft_fadd_1(v128_t dest, v128_t src);
v128_t soft_fmul_1(v128_t dest, v128_t src);

v128_t hard_fadd_1(v128_t dest, v128_t src);
v128_t hard_fmul_1(v128_t dest, v128_t src);
